# Generated by Django 3.2.11 on 2022-03-30 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo_hasna_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='img',
            field=models.ImageField(default=1, upload_to='images'),
            preserve_default=False,
        ),
    ]
